### ISSUE TITLE
Issue

### ISSUE THREAD

**Issue by Anna-Anastasia** [CloudChaan/MyStaticPages#1]
@CloudChaan

**Comment by Anna-Anastasia** [comment]
hi...?

**Comment by CloudChaan** [comment]
> hi...?

*Pet~pet~

**Comment by CloudChaan** [comment]
> hi...?

Why can't we choose a normal way to chat?

**Comment by Anna-Anastasia** [comment]
plz send a message to my outlook mail thx... i cant reach u any other way...

**Comment by CloudChaan** [comment]
me think we can just use ... bilibili?
________________________________
发件人: Anna Anastasia ***@***.***>
发送时间: 2024年1月13日 22:43
收件人: CloudChaan/MyStaticPages ***@***.***>
抄送: 云海 ***@***.***>; Mention ***@***.***>
主题: Re: [CloudChaan/MyStaticPages] Issue (Issue #1)


plz send a message to my outlook mail thx... i cant reach u any other way...

―
